- index.js
https://github.com/facebook/react/blob/0.13-stable/src/classic/element/ReactElement.js#L184-L191
`defaultProps` of `targetComponent` will be overwritten by `sourceComponent`'s.
add `defaultProps` in `REACT_STATICS`.
The case is if `targetComponent` relay on defaultProps without error handling, will cause error.
> add defaultProps in REACT_STATICS

- index.js
- tests/unit/index.js
Ran into this problem with some higher order components wrapping plain string components.
`Object.getOwnPropertyNames` ran on a string, such as `Object.getOwnPropertyNames('div')` outputs: `["0", "1", "2", "length"]`, and copies over those properties. This PR avoids copying properties from strings.
> Do not hoist properties from string components

- index.js
- tests/unit/index.js
Support copying symbol properties to make this function more `Object.assign` like.
Native `Object.assign` copies both string and symbol properties. [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign).
This might be useful when wrapped component was annotated using Symbol to exclude name collision.
> Adds support for copying static symbol properties.

- package.json
As documented on the NPM documentation (https://docs.npmjs.com/files/package.json#license). The license field has to comply with the SPDX specification for communicating the licenses and copyrights associated with a software package.
From the `LICENSE.md`, I got, that you are using `BSD-3-Clause`.
Merging this PR would improve a lot of lives, as parsing SPDX expressions is much easier than everything else.
Thank you for your time 👍
> add valid license to package.json

- .eslintrc
- package.json
Although ESLint doesn't test linting rules for any files within `node_modules`, it can still fall over `.eslintrc` config files within `node_modules` that it perceives as invalid, and it looks like the rules have become stricter and `false` is no longer accepted. Instead, you now get an error like this:
~~~
/Users/dchamb/dev/hoist-non-react-statics/.eslintrc:
Configuration for rule "no-alert" is invalid:
Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed 'false').
Error: /Users/dchamb/dev/hoist-non-react-statics/.eslintrc:
Configuration for rule "no-alert" is invalid:
Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed 'false').
~~~
Although it could be argued that ESLint should support older config even if it was using …
> Modernize eslint config

- .travis.yml
- index.js
- package.json
- tests/.babelrc
- tests/unit/index.js
This would be a major release (2.0.0) as it no longer hoists non-enumerables and there is new behavior to support hoisting inherited static class properties. 
Resolves #11 and #22.
> Simplify to enumerables + symbols and inherit statics

- index.js
- tests/unit/index.js
Resolves #29 
This changes the implementation back to using `getOwnPropertyNames`, but only hoists enumerables and non-enumerable static methods.
> Add support for non-enumerable methods

- index.d.ts
- package.json
Type definition can now be shipped with the library via npm
`index.d.ts` is the main file with declarations
`package.json` key `types` is pointing to it.
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
> Adds type definitions

- index.d.ts
hoist-non-react-statics does not have a default export and therefore saying `import hoistStatics from 'hoist-non-react-statics';` raises an exception in TS 2.4.1. Because you're using `module.exports` the correct away to require this package in TS is to say `import hoistStatics = require('hoist-non-react-statics');` but that means that the declaration file is incorrect.
Possible fixes:
1. The change proposed here
2. Change the start of [this line](https://github.com/mridgway/hoist-non-react-statics/blob/master/index.js#L35) to `exports.default = modules.exports = ...` and leave the declaration file as it is.
> TS declaration file is incorrect

- index.js
- tests/unit/index.js
This PR is a revival of #28.
First, it does something simple, which is to use `defineProperty` instead of an equality-based assignment. This is better JS hygiene when copying properties, since equality assignment results in the loss of metadata and can sometimes trigger side-effects.
Second, it removes the enumerable-or-function conditional. Judging by how the 'or-function' was added to this condition only 18 days ago (65f3d58761ea2f987689936101456d2493342ac7), I think we can reasonably agree that this condition is arbitrary. As discussed in my earlier PR (#28), both static functions and complex properties (those with getter/setter methods) are non-enumerable, and both are desirable for hoisting. However, complex properties cannot be 'detected' with a `typeof` operator.
In the end, if we …
> Generalize copying logic by using descriptors

- index.d.ts
there is a error when I use typescript to import this module like this 
`import hoistStatics from 'hoist-non-react-statics'`
because `hoistStatics` will point to `require('hoist-non-react-statics').default`
but the `module.exports.default` is undefined.
so we should import the module like this `import * as hoistStatics from 'hoist-non-react-statics'`
so I modify d.ts for typescript type system
> modify index.d.ts for typescript module

- README.md
In some other docs, `hoistNonReactStatics ` is used. 
hoistNonReactStatic in this readme may cause some mistaken.
> change hoistNonReactStatic to hoistNonReactStatics, same as the lib

- README.md
- index.js
Added `getDerivedStateFromProps`, that [will be released](https://github.com/facebook/react/issues/12152#issuecomment-362957376) with React 16.3, as a React static.
> Added getDerivedStateFromProps as React static

- index.d.ts
Currently TypeScript will resolve to the `index.d.ts` file, then consider this file to be global, and things will just work because the `declare module 'hoist-non-react-statics'` declaration still gets introduced into the program context. But if the compiler finds another `declare module 'hoist-non-react-statics'`, it may conflict.
Simply making the file itself become a module and letting Node's module resolution strategy take over can prevent global file conflicts. This PR does just that.
> Remove unnecessary ambient module declaration.

- package.json
Since the Typescript types have been removed ( #53 ), this removes the `types` key from package.json. Have a nice day!
> Removing "types" key from package.json

- src/index.js
- [Added](https://reactjs.org/blog/2018/10/23/react-v-16-6.html#static-getderivedstatefromerror) in `react@16.6.0`
- [documentation](https://reactjs.org/docs/react-component.html#static-getderivedstatefromerror)
> Add getDerivedStateFromError to the list of known REACT_STATICS

- README.md
- package.json
- src/index.js
Fixes #65.
This is no longer a requirement since we do not need to require React anymore.
> Remove React peer dependency

- package.json
- src/index.js
- tests/unit/index.js
- yarn.lock
[`React.memo` statics](https://github.com/facebook/react/blob/4a1072194fcef2da1aae2510886c274736017fbd/packages/react/src/memo.js#L27-L31)
`ReactIs.isMemo` is working differently than `ReactIs.isForwardRef` which is why we don't have to introspect `$$typeof` here.
> Prevent hoisting of React.memo statics

- src/index.js
Looks like we don't need that additional return inside the if statement. Tests pass without it too.
> remove unwanted return

- package.json
- rollup.config.js
- src/index.js
- yarn.lock
Currently umd calls not defined `require` function. In this diff I
bundled `react-is` in umd to let it work in browsers.
Nothing is changed for cjs build.
Closes https://github.com/mridgway/hoist-non-react-statics/pull/77 and https://github.com/mridgway/hoist-non-react-statics/pull/58
/cc @mridgway @Andarist
> Fix umd bundle

- src/index.js
- tests/unit/index.js
- yarn.lock
@mridgway 
The `react-is` semantics around memo components changed in v16.12, as seen in this PR: https://github.com/facebook/react/pull/17278
The `isMemo` check in this project no longer passes, which results in invalid wrapped components. For example, before my patch, the `$$typeof` was being copied over, but `type` was not, which crashed `react-test-renderer`.
```
{ Button:
{ '$$typeof': Symbol(react.memo),
type: [Function],
compare: null,
test: 'foo' } }
{ WrappedButton:
{ [Function: Wrapper] '$$typeof': Symbol(react.memo), compare: null, test: 'foo' } }
```
With my patch, the `$$typeof` is no longer copied. It also supports both types of memo checks for the time being.
```
{ Button:
{ '$$typeof': Symbol(react.memo),
type: [Function],
compare: null,
test: 'foo' } }
{ WrappedButton: { …
```
> Fix `React.memo` for v16.12+
